### ISSUE TITLE
Legend

### ISSUE THREAD

**Issue by mcwoody** [minillinim/stackedBarGraph#1]
How do you create a legend indicating what each color represents?

**Comment by minillinim** [comment]
Good question. 

There's currently no straight forward way to do it with the code. I generally make the legend separately, which is not ideal. But y'know.... ....busy

Definitely something I'd like to get around to doing.

**Comment by sven-mayer** [comment]
a legend would be perfect looking forward to an update.

**Comment by wendymungovan** [comment]
I fixed it on this fork: [Forked stackedBarGraph](https://github.com/Barnstorm-Research/stackedBarGraph)

just set the labels=['color1label','color2label'...] and the legend will be generated.

**Comment by GeorgRokne** [comment]
Hi! I've tried to get the stacked bar graph (in combination with a line on second y-axis), with labels for the bar-series. But it seems like I get different colors on the labels:
![image](https://cloud.githubusercontent.com/assets/23313132/20059946/0e3e36c4-a4f9-11e6-9acd-efe856f152f3.png)

Grateful for any help!

Code:
`import pandas as pd
import numpy as np
import math
import datetime as dt
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from stackedBarGraph import StackedBarGrapher
SBG = StackedBarGrapher()

dfx_name="Test"
dfx= pd.DataFrame(50+20_np.abs(np.random.randn(24, 9)), columns=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']) 
#dfx=dfx.reset_index()
dfx.index=dfx.index+1 
dfx.index.name = 'Time'  
dfx.insert(0, 'Pris',10+10_np.abs(np.random.randn(24)))
pris=dfx.ix[:,0]
prismax=5_math.ceil(0.2_max(pris))
prod=dfx.ix[:,1:]
prodsum=prod.sum(axis=1)
prodmax=100_math.ceil(0.01_max(prodsum))
d_colors = ['#dd1343', '#133cdd', '#13dd21', '#fcf123', '#c223fc', '#fcbe23', '#23fce6', '#fc23a9', '#5583a0']
d_colors=d_colors[0:len(prod.columns)]
labels=['color1label','color2label','color3label','color4label','color5label','color6label','color7label','color8label','color9label']
labels=labels[0:len(prod.columns)]

ax1=prod.plot(kind='bar');plt.xticks()
ax1.set_xlabel('Time')
ax1.set_ylabel('MWh')  
SBG.stackedBarPlot(ax1,
                   prod,
                   d_colors,
                   xLabels=dfx.index,
                   edgeCols=['#000000']*len(prod.columns),
                    yTicks=2,
                    gap=0.2,
                    )
plt.title(dfx_name + ' - ProdPlan '+ dt.datetime.today().strftime('%d.%m.%Y'))  
plt.legend(loc=1,prop={'size':6})
x1,x2,y1,y2 = plt.axis()
plt.axis((x1,x2,0,prodmax)) 

ax2 = ax1.twinx()    #se http://stackoverflow.com/questions/19941685/how-to-show-a-bar-and-line-graph-on-the-same-plot
ax2.plot(pris)
ax2.set_xlabel('Time')
ax2.set_ylabel('€/MWh', color='b') #, color='r'
x1,x2,y1,y2 = plt.axis()
plt.axis((x1,x2,0,prismax))  
filnavn=dfx_name + '_plot.pdf'
try:
    pp2 = PdfPages(r'C:\PythonMads\git\ProdPlan'+'\'+filnavn)
except Exception as e:
    print(e)
plt.savefig(pp2, format='pdf', papertype='a4')
pp2.close()    `

**Comment by wendymungovan** [comment]
Hi,
  There are a couple of things.  
ax1=prod.plot(kind='bar')  <<< is setting up the labels A..I instead of using the stackedBarGrapher to set the labels.  Here just use an empty plot area  add_subplot(111) or something similar.

then pass in the data to SBG.stackedBarPlot(ax1,plod.as_matrix(),...., labels=labels) adding in the labels.  You can pass in the x and y labels using xlabels="Time", ylabels="MWh".

This is still not quite what you want I did not fight with prod to remove the line from the matrix.  Because of this when you pass in the d_colors and labels you need to include the line color.

![figure_1](https://cloud.githubusercontent.com/assets/10120642/20101271/37bf443e-a58f-11e6-9406-0b9d9e27dbee.png)

**Comment by GeorgRokne** [comment]
Hi @wendymungovan ! Thanks for your response!
I've found another way of setting the labels identical to the bar colors by using mpatches. It works!
Now i have to fix the scale of my y-axis - it's quite messed up :-)

BR, Georg
